default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: "22.3.0"
    hooks:
      - id: black
        args:
          - --line-length=88
        exclude: (migrations/.*)
  - repo: https://github.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        args: ["--config=.flake8"]
  - repo: https://github.com/godaddy/tartufo
    rev: v3.1.3
    hooks:
      - id: tartufo
        language: python
        args: [ "-xp", "docs/", "pre-commit" ]
